# Generated by Django 6.0.4 on 2026-05-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
