# Generated by Django 6.0.4 on 2026-04-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_answer',
            new_name='correct_option',
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
