# Generated by Django 6.0.4 on 2026-04-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_rename_correct_answer_question_correct_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
    ]
