# Generated by Django 6.0.4 on 2026-05-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_rename_created_at_result_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(max_length=1),
        ),
    ]
