# Generated by Django 6.0.4 on 2026-05-08 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_enrollment_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='is_completed',
        ),
    ]
